CREATE DATABASE wol;
USE wol;
CREATE TABLE users(
idUsers int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
uid TINYTEXT NOT NULL,
pwd LONGTEXT NOT NULL,
ROLE TINYTEXT NOT NULL
);
CREATE TABLE auth (
	id int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    token TINYTEXT NOT NULL,
    name TINYTEXT NOT NULL,
    used BIT default 0
);
